# This is a basic workflow to help you get started with Actions

name: Create pdf release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Setup emacs
      - name: Set up Emacs
        uses: purcell/setup-emacs@v3.0
        with:
          version: 27.2
        
      - name: Compile org to tex
        run: |
           emacs -Q --batch -nw Chapters/outline-anyons.org --eval "(progn \
           (setq org-export-with-broken-links t) \
           (require 'org) \
           (require 'ox-latex) \
           (seq-doseq (file (directory-files "./Chapters" t ".org")) \
           (with-temp-file file \
             (org-export-to-file 'latex (concat "Chapters/" (file-name-base file) ".tex")))))"

      # Do latex
      - name: Github Action for LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: | 
            "Chapters/*.tex"
            
          args: -pdf -file-line-error -interaction=nonstopmode -f


      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "Chapters/*.pdf"
