
name: "Todo"
on: ["push"]
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2.3.1"
      - name: TODO to Issue (MDX support)
        uses: ThomasFKJorna/todo-to-issue-action@v4.7

        id: "todo"
